/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConsumerDevice
 */

public class ConsumerDevice {
  @SerializedName("imei")
  private String imei = null;

  @SerializedName("serialNumber")
  private String serialNumber = null;

  public ConsumerDevice imei(String imei) {
    this.imei = imei;
    return this;
  }

   /**
   * The consumer’s device international mobile equipment identity
   * @return imei
  **/
  @ApiModelProperty(value = "The consumer’s device international mobile equipment identity")
  public String getImei() {
    return imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public ConsumerDevice serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * The consumer&#39;s device serial number
   * @return serialNumber
  **/
  @ApiModelProperty(required = true, value = "The consumer's device serial number")
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumerDevice consumerDevice = (ConsumerDevice) o;
    return Objects.equals(this.imei, consumerDevice.imei) &&
        Objects.equals(this.serialNumber, consumerDevice.serialNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imei, serialNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumerDevice {\n");
    
    sb.append("    imei: ").append(toIndentedString(imei)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

