/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.Error;
import com.payneteasy.android.model.InitiateTransferResponseRates;
import com.payneteasy.android.model.Session;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InitiateTransferResponse
 */

public class InitiateTransferResponse {
  @SerializedName("endpointId")
  private String endpointId = null;

  @SerializedName("invoiceId")
  private String invoiceId = null;

  @SerializedName("rates")
  private InitiateTransferResponseRates rates = null;

  @SerializedName("session")
  private Session session = null;

  @SerializedName("error")
  private Error error = null;

  public InitiateTransferResponse endpointId(String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Entry point identifier for transfer transaction
   * @return endpointId
  **/
  @ApiModelProperty(value = "Entry point identifier for transfer transaction")
  public String getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(String endpointId) {
    this.endpointId = endpointId;
  }

  public InitiateTransferResponse invoiceId(String invoiceId) {
    this.invoiceId = invoiceId;
    return this;
  }

   /**
   * Transfer transaction identifier
   * @return invoiceId
  **/
  @ApiModelProperty(value = "Transfer transaction identifier")
  public String getInvoiceId() {
    return invoiceId;
  }

  public void setInvoiceId(String invoiceId) {
    this.invoiceId = invoiceId;
  }

  public InitiateTransferResponse rates(InitiateTransferResponseRates rates) {
    this.rates = rates;
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @ApiModelProperty(value = "")
  public InitiateTransferResponseRates getRates() {
    return rates;
  }

  public void setRates(InitiateTransferResponseRates rates) {
    this.rates = rates;
  }

  public InitiateTransferResponse session(Session session) {
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @ApiModelProperty(value = "")
  public Session getSession() {
    return session;
  }

  public void setSession(Session session) {
    this.session = session;
  }

  public InitiateTransferResponse error(Error error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateTransferResponse initiateTransferResponse = (InitiateTransferResponse) o;
    return Objects.equals(this.endpointId, initiateTransferResponse.endpointId) &&
        Objects.equals(this.invoiceId, initiateTransferResponse.invoiceId) &&
        Objects.equals(this.rates, initiateTransferResponse.rates) &&
        Objects.equals(this.session, initiateTransferResponse.session) &&
        Objects.equals(this.error, initiateTransferResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointId, invoiceId, rates, session, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateTransferResponse {\n");
    
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    invoiceId: ").append(toIndentedString(invoiceId)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

