/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InitiateTransferResponseRates
 */

public class InitiateTransferResponseRates {
  @SerializedName("min")
  private String min = null;

  @SerializedName("max")
  private String max = null;

  public InitiateTransferResponseRates min(String min) {
    this.min = min;
    return this;
  }

   /**
   * Possible minimum commission amount
   * @return min
  **/
  @ApiModelProperty(value = "Possible minimum commission amount")
  public String getMin() {
    return min;
  }

  public void setMin(String min) {
    this.min = min;
  }

  public InitiateTransferResponseRates max(String max) {
    this.max = max;
    return this;
  }

   /**
   * Possible maximum commission amount
   * @return max
  **/
  @ApiModelProperty(value = "Possible maximum commission amount")
  public String getMax() {
    return max;
  }

  public void setMax(String max) {
    this.max = max;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateTransferResponseRates initiateTransferResponseRates = (InitiateTransferResponseRates) o;
    return Objects.equals(this.min, initiateTransferResponseRates.min) &&
        Objects.equals(this.max, initiateTransferResponseRates.max);
  }

  @Override
  public int hashCode() {
    return Objects.hash(min, max);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateTransferResponseRates {\n");
    
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

