/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.SourceOfFundsCard;
import com.payneteasy.android.model.SourceOfFundsReference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Only one of these subtypes (card, reference) should be used
 */
@ApiModel(description = "Only one of these subtypes (card, reference) should be used")

public class SourceOfFunds {
  @SerializedName("card")
  private SourceOfFundsCard card = null;

  @SerializedName("reference")
  private SourceOfFundsReference reference = null;

  public SourceOfFunds card(SourceOfFundsCard card) {
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  @ApiModelProperty(value = "")
  public SourceOfFundsCard getCard() {
    return card;
  }

  public void setCard(SourceOfFundsCard card) {
    this.card = card;
  }

  public SourceOfFunds reference(SourceOfFundsReference reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public SourceOfFundsReference getReference() {
    return reference;
  }

  public void setReference(SourceOfFundsReference reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceOfFunds sourceOfFunds = (SourceOfFunds) o;
    return Objects.equals(this.card, sourceOfFunds.card) &&
        Objects.equals(this.reference, sourceOfFunds.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(card, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceOfFunds {\n");
    
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

