/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SourceOfFundsReference
 */

public class SourceOfFundsReference {
  @SerializedName("clientCardId")
  private String clientCardId = null;

  @SerializedName("securityCode")
  private String securityCode = null;

  public SourceOfFundsReference clientCardId(String clientCardId) {
    this.clientCardId = clientCardId;
    return this;
  }

   /**
   * Source card reference identifier (on client side)
   * @return clientCardId
  **/
  @ApiModelProperty(required = true, value = "Source card reference identifier (on client side)")
  public String getClientCardId() {
    return clientCardId;
  }

  public void setClientCardId(String clientCardId) {
    this.clientCardId = clientCardId;
  }

  public SourceOfFundsReference securityCode(String securityCode) {
    this.securityCode = securityCode;
    return this;
  }

   /**
   * Source card security code (CVV)
   * @return securityCode
  **/
  @ApiModelProperty(required = true, value = "Source card security code (CVV)")
  public String getSecurityCode() {
    return securityCode;
  }

  public void setSecurityCode(String securityCode) {
    this.securityCode = securityCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceOfFundsReference sourceOfFundsReference = (SourceOfFundsReference) o;
    return Objects.equals(this.clientCardId, sourceOfFundsReference.clientCardId) &&
        Objects.equals(this.securityCode, sourceOfFundsReference.securityCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientCardId, securityCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceOfFundsReference {\n");
    
    sb.append("    clientCardId: ").append(toIndentedString(clientCardId)).append("\n");
    sb.append("    securityCode: ").append(toIndentedString(securityCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

