/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.SourceOfFundsCardExpiry;
import com.payneteasy.android.model.SourceOfFundsCardHolder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SourceOfFundsCard
 */

public class SourceOfFundsCard {
  @SerializedName("number")
  private String number = null;

  @SerializedName("expiry")
  private SourceOfFundsCardExpiry expiry = null;

  @SerializedName("holder")
  private SourceOfFundsCardHolder holder = null;

  @SerializedName("securityCode")
  private String securityCode = null;

  public SourceOfFundsCard number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Source card number (PAN)
   * @return number
  **/
  @ApiModelProperty(required = true, value = "Source card number (PAN)")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public SourceOfFundsCard expiry(SourceOfFundsCardExpiry expiry) {
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @ApiModelProperty(value = "")
  public SourceOfFundsCardExpiry getExpiry() {
    return expiry;
  }

  public void setExpiry(SourceOfFundsCardExpiry expiry) {
    this.expiry = expiry;
  }

  public SourceOfFundsCard holder(SourceOfFundsCardHolder holder) {
    this.holder = holder;
    return this;
  }

   /**
   * Get holder
   * @return holder
  **/
  @ApiModelProperty(value = "")
  public SourceOfFundsCardHolder getHolder() {
    return holder;
  }

  public void setHolder(SourceOfFundsCardHolder holder) {
    this.holder = holder;
  }

  public SourceOfFundsCard securityCode(String securityCode) {
    this.securityCode = securityCode;
    return this;
  }

   /**
   * Source card security code (CVV)
   * @return securityCode
  **/
  @ApiModelProperty(required = true, value = "Source card security code (CVV)")
  public String getSecurityCode() {
    return securityCode;
  }

  public void setSecurityCode(String securityCode) {
    this.securityCode = securityCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceOfFundsCard sourceOfFundsCard = (SourceOfFundsCard) o;
    return Objects.equals(this.number, sourceOfFundsCard.number) &&
        Objects.equals(this.expiry, sourceOfFundsCard.expiry) &&
        Objects.equals(this.holder, sourceOfFundsCard.holder) &&
        Objects.equals(this.securityCode, sourceOfFundsCard.securityCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, expiry, holder, securityCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceOfFundsCard {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    holder: ").append(toIndentedString(holder)).append("\n");
    sb.append("    securityCode: ").append(toIndentedString(securityCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

