/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SourceOfFundsCardExpiry
 */

public class SourceOfFundsCardExpiry {
  @SerializedName("month")
  private Integer month = null;

  @SerializedName("year")
  private Integer year = null;

  public SourceOfFundsCardExpiry month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * Source Card expiration month
   * @return month
  **/
  @ApiModelProperty(required = true, value = "Source Card expiration month")
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public SourceOfFundsCardExpiry year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Source Card expiration year
   * @return year
  **/
  @ApiModelProperty(required = true, value = "Source Card expiration year")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceOfFundsCardExpiry sourceOfFundsCardExpiry = (SourceOfFundsCardExpiry) o;
    return Objects.equals(this.month, sourceOfFundsCardExpiry.month) &&
        Objects.equals(this.year, sourceOfFundsCardExpiry.year);
  }

  @Override
  public int hashCode() {
    return Objects.hash(month, year);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceOfFundsCardExpiry {\n");
    
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

