/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CardsIdsResponse
 */

public class CardsIdsResponse {
  @SerializedName("sourceCardRefId")
  private String sourceCardRefId = null;

  @SerializedName("destinationCardRefId")
  private String destinationCardRefId = null;

  @SerializedName("error")
  private Error error = null;

  public CardsIdsResponse sourceCardRefId(String sourceCardRefId) {
    this.sourceCardRefId = sourceCardRefId;
    return this;
  }

   /**
   * The source card reference identifier (on client side)
   * @return sourceCardRefId
  **/
  @ApiModelProperty(value = "The source card reference identifier (on client side)")
  public String getSourceCardRefId() {
    return sourceCardRefId;
  }

  public void setSourceCardRefId(String sourceCardRefId) {
    this.sourceCardRefId = sourceCardRefId;
  }

  public CardsIdsResponse destinationCardRefId(String destinationCardRefId) {
    this.destinationCardRefId = destinationCardRefId;
    return this;
  }

   /**
   * The destination card reference identifier (on client side)
   * @return destinationCardRefId
  **/
  @ApiModelProperty(value = "The destination card reference identifier (on client side)")
  public String getDestinationCardRefId() {
    return destinationCardRefId;
  }

  public void setDestinationCardRefId(String destinationCardRefId) {
    this.destinationCardRefId = destinationCardRefId;
  }

  public CardsIdsResponse error(Error error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Error getError() {
    return error;
  }

  public void setError(Error error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardsIdsResponse cardsIdsResponse = (CardsIdsResponse) o;
    return Objects.equals(this.sourceCardRefId, cardsIdsResponse.sourceCardRefId) &&
        Objects.equals(this.destinationCardRefId, cardsIdsResponse.destinationCardRefId) &&
        Objects.equals(this.error, cardsIdsResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceCardRefId, destinationCardRefId, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardsIdsResponse {\n");
    
    sb.append("    sourceCardRefId: ").append(toIndentedString(sourceCardRefId)).append("\n");
    sb.append("    destinationCardRefId: ").append(toIndentedString(destinationCardRefId)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

