/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.Error;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * CommissionResponse
 */

public class CommissionResponse {

  @SerializedName("commissionCentis")
  private Long commissionCentis = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("error")
  private Error error = null;
  public CommissionResponse commissionCentis(Long commissionCentis) {
    this.commissionCentis = commissionCentis;
    return this;
  }

  

  /**
  * Commission amount, 1.00 EUR &#x3D; 100 centis
  * @return commissionCentis
  **/
  @Schema(description = "Commission amount, 1.00 EUR = 100 centis")
  public Long getCommissionCentis() {
    return commissionCentis;
  }
  public void setCommissionCentis(Long commissionCentis) {
    this.commissionCentis = commissionCentis;
  }
  public CommissionResponse currency(String currency) {
    this.currency = currency;
    return this;
  }

  

  /**
  * Transaction currency, upper case letters (ISO 4217 alpha code)
  * @return currency
  **/
  @Schema(description = "Transaction currency, upper case letters (ISO 4217 alpha code)")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }
  public CommissionResponse error(Error error) {
    this.error = error;
    return this;
  }

  

  /**
  * Get error
  * @return error
  **/
  @Schema(description = "")
  public Error getError() {
    return error;
  }
  public void setError(Error error) {
    this.error = error;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommissionResponse commissionResponse = (CommissionResponse) o;
    return Objects.equals(this.commissionCentis, commissionResponse.commissionCentis) &&
        Objects.equals(this.currency, commissionResponse.currency) &&
        Objects.equals(this.error, commissionResponse.error);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(commissionCentis, currency, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommissionResponse {\n");
    
    sb.append("    commissionCentis: ").append(toIndentedString(commissionCentis)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
