/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.Consumer;
import com.payneteasy.android.model.Session;
import com.payneteasy.android.model.Transaction;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * CommissionRequest
 */

public class CommissionRequest {

  @SerializedName("session")
  private Session session = null;

  @SerializedName("consumer")
  private Consumer consumer = null;

  @SerializedName("transaction")
  private Transaction transaction = null;
  public CommissionRequest session(Session session) {
    this.session = session;
    return this;
  }

  

  /**
  * Get session
  * @return session
  **/
  @Schema(required = true, description = "")
  public Session getSession() {
    return session;
  }
  public void setSession(Session session) {
    this.session = session;
  }
  public CommissionRequest consumer(Consumer consumer) {
    this.consumer = consumer;
    return this;
  }

  

  /**
  * Get consumer
  * @return consumer
  **/
  @Schema(required = true, description = "")
  public Consumer getConsumer() {
    return consumer;
  }
  public void setConsumer(Consumer consumer) {
    this.consumer = consumer;
  }
  public CommissionRequest transaction(Transaction transaction) {
    this.transaction = transaction;
    return this;
  }

  

  /**
  * Get transaction
  * @return transaction
  **/
  @Schema(description = "")
  public Transaction getTransaction() {
    return transaction;
  }
  public void setTransaction(Transaction transaction) {
    this.transaction = transaction;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommissionRequest commissionRequest = (CommissionRequest) o;
    return Objects.equals(this.session, commissionRequest.session) &&
        Objects.equals(this.consumer, commissionRequest.consumer) &&
        Objects.equals(this.transaction, commissionRequest.transaction);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(session, consumer, transaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommissionRequest {\n");
    
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    consumer: ").append(toIndentedString(consumer)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
