/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.DestinationOfFundsCard;
import com.payneteasy.android.model.DestinationOfFundsReference;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Only one of these subtypes (card, reference) should be used
 */
@Schema(description = "Only one of these subtypes (card, reference) should be used")
public class DestinationOfFunds {

  @SerializedName("card")
  private DestinationOfFundsCard card = null;

  @SerializedName("reference")
  private DestinationOfFundsReference reference = null;
  public DestinationOfFunds card(DestinationOfFundsCard card) {
    this.card = card;
    return this;
  }

  

  /**
  * Get card
  * @return card
  **/
  @Schema(required = true, description = "")
  public DestinationOfFundsCard getCard() {
    return card;
  }
  public void setCard(DestinationOfFundsCard card) {
    this.card = card;
  }
  public DestinationOfFunds reference(DestinationOfFundsReference reference) {
    this.reference = reference;
    return this;
  }

  

  /**
  * Get reference
  * @return reference
  **/
  @Schema(description = "")
  public DestinationOfFundsReference getReference() {
    return reference;
  }
  public void setReference(DestinationOfFundsReference reference) {
    this.reference = reference;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DestinationOfFunds destinationOfFunds = (DestinationOfFunds) o;
    return Objects.equals(this.card, destinationOfFunds.card) &&
        Objects.equals(this.reference, destinationOfFunds.reference);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(card, reference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DestinationOfFunds {\n");
    
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
