/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PerformTransferRequest
 */

public class PerformTransferRequest {
  @SerializedName("consumer")
  private Consumer consumer = null;

  @SerializedName("sourceOfFunds")
  private SourceOfFunds sourceOfFunds = null;

  @SerializedName("destinationOfFunds")
  private DestinationOfFunds destinationOfFunds = null;

  @SerializedName("transaction")
  private Transaction transaction = null;

  @SerializedName("session")
  private Session session = null;

  public PerformTransferRequest consumer(Consumer consumer) {
    this.consumer = consumer;
    return this;
  }

   /**
   * Get consumer
   * @return consumer
  **/
  @ApiModelProperty(required = true, value = "")
  public Consumer getConsumer() {
    return consumer;
  }

  public void setConsumer(Consumer consumer) {
    this.consumer = consumer;
  }

  public PerformTransferRequest sourceOfFunds(SourceOfFunds sourceOfFunds) {
    this.sourceOfFunds = sourceOfFunds;
    return this;
  }

   /**
   * Get sourceOfFunds
   * @return sourceOfFunds
  **/
  @ApiModelProperty(required = true, value = "")
  public SourceOfFunds getSourceOfFunds() {
    return sourceOfFunds;
  }

  public void setSourceOfFunds(SourceOfFunds sourceOfFunds) {
    this.sourceOfFunds = sourceOfFunds;
  }

  public PerformTransferRequest destinationOfFunds(DestinationOfFunds destinationOfFunds) {
    this.destinationOfFunds = destinationOfFunds;
    return this;
  }

   /**
   * Get destinationOfFunds
   * @return destinationOfFunds
  **/
  @ApiModelProperty(required = true, value = "")
  public DestinationOfFunds getDestinationOfFunds() {
    return destinationOfFunds;
  }

  public void setDestinationOfFunds(DestinationOfFunds destinationOfFunds) {
    this.destinationOfFunds = destinationOfFunds;
  }

  public PerformTransferRequest transaction(Transaction transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @ApiModelProperty(required = true, value = "")
  public Transaction getTransaction() {
    return transaction;
  }

  public void setTransaction(Transaction transaction) {
    this.transaction = transaction;
  }

  public PerformTransferRequest session(Session session) {
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @ApiModelProperty(required = true, value = "")
  public Session getSession() {
    return session;
  }

  public void setSession(Session session) {
    this.session = session;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformTransferRequest performTransferRequest = (PerformTransferRequest) o;
    return Objects.equals(this.consumer, performTransferRequest.consumer) &&
        Objects.equals(this.sourceOfFunds, performTransferRequest.sourceOfFunds) &&
        Objects.equals(this.destinationOfFunds, performTransferRequest.destinationOfFunds) &&
        Objects.equals(this.transaction, performTransferRequest.transaction) &&
        Objects.equals(this.session, performTransferRequest.session);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consumer, sourceOfFunds, destinationOfFunds, transaction, session);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformTransferRequest {\n");
    
    sb.append("    consumer: ").append(toIndentedString(consumer)).append("\n");
    sb.append("    sourceOfFunds: ").append(toIndentedString(sourceOfFunds)).append("\n");
    sb.append("    destinationOfFunds: ").append(toIndentedString(destinationOfFunds)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

