/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.payneteasy.android.model.Session;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * SendFeedbackRequest
 */

public class SendFeedbackRequest {

  @SerializedName("message")
  private String message = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("orderId")
  private String orderId = null;

  @SerializedName("session")
  private Session session = null;
  public SendFeedbackRequest message(String message) {
    this.message = message;
    return this;
  }

  

  /**
  * Get message
  * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }
  public SendFeedbackRequest email(String email) {
    this.email = email;
    return this;
  }

  

  /**
  * Get email
  * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }
  public SendFeedbackRequest orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

  

  /**
  * Get orderId
  * @return orderId
  **/
  @Schema(description = "")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }
  public SendFeedbackRequest session(Session session) {
    this.session = session;
    return this;
  }

  

  /**
  * Get session
  * @return session
  **/
  @Schema(description = "")
  public Session getSession() {
    return session;
  }
  public void setSession(Session session) {
    this.session = session;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendFeedbackRequest sendFeedbackRequest = (SendFeedbackRequest) o;
    return Objects.equals(this.message, sendFeedbackRequest.message) &&
        Objects.equals(this.email, sendFeedbackRequest.email) &&
        Objects.equals(this.orderId, sendFeedbackRequest.orderId) &&
        Objects.equals(this.session, sendFeedbackRequest.session);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(message, email, orderId, session);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendFeedbackRequest {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
