/*
 * Payneteasy Android Transfer DAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.payneteasy.android.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Transaction
 */

public class Transaction {
  @SerializedName("endpointId")
  private String endpointId = null;

  @SerializedName("invoiceId")
  private String invoiceId = null;

  @SerializedName("amountCentis")
  private Long amountCentis = null;

  @SerializedName("commissionCentis")
  private Long commissionCentis = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("orderCreatedDate")
  private String orderCreatedDate = null;

  @SerializedName("transactionCreatedDate")
  private String transactionCreatedDate = null;

  public Transaction endpointId(String endpointId) {
    this.endpointId = endpointId;
    return this;
  }

   /**
   * Entry point identifier for transfer transaction
   * @return endpointId
  **/
  @ApiModelProperty(value = "Entry point identifier for transfer transaction")
  public String getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(String endpointId) {
    this.endpointId = endpointId;
  }

  public Transaction invoiceId(String invoiceId) {
    this.invoiceId = invoiceId;
    return this;
  }

   /**
   * Transfer transaction identifier
   * @return invoiceId
  **/
  @ApiModelProperty(value = "Transfer transaction identifier")
  public String getInvoiceId() {
    return invoiceId;
  }

  public void setInvoiceId(String invoiceId) {
    this.invoiceId = invoiceId;
  }

  public Transaction amountCentis(Long amountCentis) {
    this.amountCentis = amountCentis;
    return this;
  }

   /**
   * Transaction amount, 1.00 EUR &#x3D; 100 centis
   * @return amountCentis
  **/
  @ApiModelProperty(value = "Transaction amount, 1.00 EUR = 100 centis")
  public Long getAmountCentis() {
    return amountCentis;
  }

  public void setAmountCentis(Long amountCentis) {
    this.amountCentis = amountCentis;
  }

  public Transaction commissionCentis(Long commissionCentis) {
    this.commissionCentis = commissionCentis;
    return this;
  }

   /**
   * Amount of commission held in centis
   * @return commissionCentis
  **/
  @ApiModelProperty(value = "Amount of commission held in centis")
  public Long getCommissionCentis() {
    return commissionCentis;
  }

  public void setCommissionCentis(Long commissionCentis) {
    this.commissionCentis = commissionCentis;
  }

  public Transaction currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Transaction currency, upper case letters (ISO 4217 alpha code)
   * @return currency
  **/
  @ApiModelProperty(value = "Transaction currency, upper case letters (ISO 4217 alpha code)")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Transaction orderCreatedDate(String orderCreatedDate) {
    this.orderCreatedDate = orderCreatedDate;
    return this;
  }

   /**
   * Order creation date in payment processing system
   * @return orderCreatedDate
  **/
  @ApiModelProperty(value = "Order creation date in payment processing system")
  public String getOrderCreatedDate() {
    return orderCreatedDate;
  }

  public void setOrderCreatedDate(String orderCreatedDate) {
    this.orderCreatedDate = orderCreatedDate;
  }

  public Transaction transactionCreatedDate(String transactionCreatedDate) {
    this.transactionCreatedDate = transactionCreatedDate;
    return this;
  }

   /**
   * Transaction creation date in payment processing system
   * @return transactionCreatedDate
  **/
  @ApiModelProperty(value = "Transaction creation date in payment processing system")
  public String getTransactionCreatedDate() {
    return transactionCreatedDate;
  }

  public void setTransactionCreatedDate(String transactionCreatedDate) {
    this.transactionCreatedDate = transactionCreatedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.endpointId, transaction.endpointId) &&
        Objects.equals(this.invoiceId, transaction.invoiceId) &&
        Objects.equals(this.amountCentis, transaction.amountCentis) &&
        Objects.equals(this.commissionCentis, transaction.commissionCentis) &&
        Objects.equals(this.currency, transaction.currency) &&
        Objects.equals(this.orderCreatedDate, transaction.orderCreatedDate) &&
        Objects.equals(this.transactionCreatedDate, transaction.transactionCreatedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointId, invoiceId, amountCentis, commissionCentis, currency, orderCreatedDate, transactionCreatedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    invoiceId: ").append(toIndentedString(invoiceId)).append("\n");
    sb.append("    amountCentis: ").append(toIndentedString(amountCentis)).append("\n");
    sb.append("    commissionCentis: ").append(toIndentedString(commissionCentis)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    orderCreatedDate: ").append(toIndentedString(orderCreatedDate)).append("\n");
    sb.append("    transactionCreatedDate: ").append(toIndentedString(transactionCreatedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

